[package]
name = "codecrafters-dns-server"
version = "0.1.0"
authors = ["Codecrafters <hello@codecrafters.io>"]
edition = "2021"
rust-version = "1.80"

[dependencies]
anyhow = "1"
bytes = "1"
thiserror = "2"
deku = "*"
clap = { version = "4", features = ["derive"] } # command line argument parsing
